version: '3.8'

services:
  app:
    image: nyt-best-sellers
    container_name: nyt-best-sellers
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
